image: "python:3.7"

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

stages:
  - Static Analysis
  - Test

black:
  stage: Static Analysis
  only:
    - merge_requests
  script:
    - pip install black==19.3b0
    - black --check biometrics_client

safety:
  stage: Static Analysis
  script:
  - pip install safety  # We want the latest of this.
  - python setup.py install  # Only check the installed production packages.
  - pip freeze | safety check --stdin  # This way so we check transitive dependencies.

bandit:
  stage: Static Analysis
  script:
  - pip install bandit  # We want the latest of this.
  - bandit -r models biometrics_client

unit_test:
  stage: Test
  only:
    - merge_requests
  script:
    - python setup.py install
    - bash tests/run.sh
